#! /usr/bin/expect
#################################################
# Copyright 2017-2023 HaojueWang <acewhj@gmail.com>
# All Rights Reserved.
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#################################################
set IP   [lindex $argv 0]
set USER [lindex $argv 1]
set PASS [lindex $argv 2]
#set PASS MaRtInI
#set FILE [lindex $argv 3]
set FILE1 utm_aaaa.bin
set FILE2 utm_bbbb.bin


proc do_console_login {ip user pass file1 file2} {

        set prompt "ftp>"
#        set file exp1.sh

        spawn ftp $ip
                     expect   "):"
                     send "$user\r"
                     expect   "Password :"
                     send "$pass\r"
                     expect "$prompt"
                     send "bin\r"
                     expect "$prompt" 
                     send "cd /Users/haojue\r"
                     expect "$prompt"
                     send "get $file1\r"
                     sleep 5 
                     expect "$prompt"
                     send "get $file2\r"
                     sleep 5
                     expect "$prompt"
		     send "bye\r"
                     expect ">>"  

}

if {$argc<3} {

        puts stderr "Usage: $argv0 ip username password\n "
        exit 1
}

do_console_login $IP $USER $PASS $FILE1 $FILE2 

close

exit 0
